import cv2 as cv
import numpy as np
img=cv.imread('photos/1.png')
b,g,r= cv.split(img)
cv.imshow('og', img)
cv.imshow('blue', b)
cv.imshow('green', g)
cv.imshow("red", r)
print(img.shape)
print(b.shape)
print(r.shape)
print(g.shape)
blank=np.zeros(img.shape[:2], dtype='uint8')
merged= cv.merge([b,blank,blank])
cv.imshow("merged", merged)
cv.waitKey(0)